### PR TITLE
Update for Matomo 5 compatibility

### PR DESCRIPTION
**Pull request by snake14**
Dear Matomo Plugin Author,
We are excited that Matomo 5.0.0 is on the horizon, and we would greatly appreciate your assistance in ensuring that your plugin remains compatible with this upcoming release. Maintaining compatibility will enable Matomo users to seamlessly use your plugin after they upgrade to Matomo 5. (If the plugin is not updated to be compatible with Matomo 5, then whenever a user will upgrade to Matomo 5, the plugin would be automatically disabled to prevent issues.)

Updating your plugin to be Matomo 5 compatible is a straightforward process and should not require a significant time investment. You can find more information about updating your plugin at: https://developer.matomo.org/guides/migrate-matomo-4-to-5

Thank you for your ongoing support and commitment to the Matomo community. 
Your contribution is really appreciated!

The Matomo Team

PS: we’re also available to help if you have any question about making the plugin compatible.

> I took the liberty of forking this project and making the necessary changes. If you create a `5.x-dev` branch, rebase this PR to that branch, merge the PR, and create a new release, you should be good to go. **NOTE:** The reason I advise creating a new `5.x-dev` branch instead of merging into master is so that you can continue to maintain your plugin for older versions of Matomo.

### CODE REVIEW

**Comment by snake14** [comment]
@MichaelRoosz Please create a `5.x` branch, rebase this PR to that branch, and merge. If you have any concerns or questions, please let me know.

**Comment by snake14** [comment]
Hi @MichaelRoosz . I just wanted to follow up and see if you had any concerns or questions about this PR?

**Comment by MichaelRoosz** [comment]
Hello @snake14,

thank you for your contribution!

**Comment by ludopaquet** [comment]
Hello @snake14 ,
Seems the Sites Selector is broken in 5.0 branch, think we should migrate it to use vue.js I guess, any recommandation/example on your side ?
https://github.com/MichaelRoosz/plugin-GroupPermissions/blob/5.x/templates/_access.twig#L10C32-L10C32


Many thanks

**Comment by snake14** [comment]
> Hello @snake14 , Seems the Sites Selector is broken in 5.0 branch, think we should migrate it to use vue.js I guess, any recommandation/example on your side ? https://github.com/MichaelRoosz/plugin-GroupPermissions/blob/5.x/templates/_access.twig#L10C32-L10C32 
> 
> Many thanks

Hi @ludopaquet . Sorry I missed that. You'd need something like this:
```
<div
    vue-entry="CoreHome.SiteSelector"
    show-selected-site="true"
    class="sites_autocomplete"
    only-sites-with-admin-access="true"
    switch-site-on-select="false"
    all-sites-text="{{ applyAllSitesText }}"
    all-sites-location="bottom"
    name="{{ defaultReportSiteName }}"
    id="groupPermissionsSiteSelect"
></div>
```

Here's [some documentation about it](https://developer.matomo.org/guides/vue-getting-started#using-vue-components-outside-of-vue) and [this is the source code for the component](https://github.com/matomo-org/matomo/blob/e9b3ab180d7ca289d3951ddfda052a7151edd415/plugins/CoreHome/vue/src/SiteSelector/SiteSelector.vue#L141). Here's a [basic example](https://github.com/matomo-org/matomo/blob/c03316e1c1d62585f45355f062d1a7b6eaaa82a8/plugins/CustomDimensions/templates/manage.twig#L5) of where it's used in Matomo. Please let me know if you need any further assistance.

**Comment by ludopaquet** [comment]
@snake14 many thanks for your help. I am able now to display the site selector but seems the choice is not taken into account. I am new to Vue / Matomo plugin, I need to check further the documentation to understand how to catch correctly the change event. I let you know in any case.

**Comment by snake14** [comment]
> @snake14 many thanks for your help. I am able now to display the site selector but seems the choice is not taken into account. I am new to Vue / Matomo plugin, I need to check further the documentation to understand how to catch correctly the change event. I let you know in any case.

@ludopaquet I'm glad that I could help. Things get more tricky if you need to listen for events. The easiest way I know of is to surround the SiteSelector component with your own custom Vue component and [listen for the event like this](https://github.com/matomo-org/matomo/blob/ca1b52a5e0113ce40f172ae337e93f86e1c8d831/plugins/CorePluginsAdmin/vue/src/FormField/FieldSite.vue#L13).

**Pull request merged**
